Repository szczepienia-pw/backend, pull requests merged in 2022-05, with the labels that each got.

#51 [SP-149] QR code in vaccination certificate
  app/Controllers/Patient/VaccinationController.cs
  app/Helpers/CertificateGenerator.cs
  app/Services/Patient/VaccinationService.cs
  app/backend.csproj
  tests/Helpers/DbHelper.cs
  tests/Unit/Helpers/CertificateGeneratorTest.cs
  tests/Unit/Services/Admin/AdminPatientsServiceTest.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
  tests/backend-tests.csproj
Labels: enhancement

#53 [SP-250] Fix QR code generator in Linux
  app/Helpers/CertificateGenerator.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: bug

#54 [SP-191] Fix NullReferenceException in AvailableSlotResponse
  app/Dto/Responses/Patient/Vaccination/VaccinationResponse.cs
  app/Services/Patient/VaccinationService.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: bug

#52 [SP-191] Integration Tests
  app/Controllers/Admin/AdminAuthController.cs
  app/Controllers/Doctor/DoctorAuthController.cs
  app/Controllers/Patient/PatientAuthController.cs
  app/Database/DataContext.cs
  app/Database/DataContextExtensions.cs
  app/Database/Seeder.cs
  app/Dto/Requests/Patient/FilterVaccinationsRequest.cs
  app/Dto/Responses/ErrorResponse.cs
  app/Exceptions/BasicException.cs
  app/Exceptions/ConflictException.cs
  app/Exceptions/NotFoundException.cs
  app/Exceptions/UnauthorizedException.cs
  app/Exceptions/ValidationException.cs
  app/Helpers/AuthorizeAttribute.cs
  app/Helpers/CertificateGenerator.cs
  app/Helpers/EnumberableExtensions.cs
  app/Helpers/JwtGenerator.cs
  app/Helpers/MailSettings.cs
  app/Helpers/Mailer.cs
  app/Helpers/PaginatedList.cs
  app/Helpers/Program.cs
  app/Helpers/SecurePasswordHasher.cs
  app/Helpers/Validator.cs
  app/Middlewares/ErrorHandlerMiddleware.cs
  app/Program.cs
  app/Validators/Requests/Doctor/VaccinationSlot/FilterVaccinationSlotValidator.cs
  app/Validators/Requests/Patient/FilterVaccinationsValidator.cs
  tests/Integration/Controllers/Admin/AdminAuthController.cs
  tests/Integration/Controllers/Admin/AdminDoctorsController.cs
  tests/Integration/Controllers/Admin/AdminPatientsController.cs
  tests/Integration/Controllers/Admin/SettingsControllerTests.cs
  tests/Integration/Controllers/BugControllerTests.cs
  tests/Integration/Controllers/CommonVaccinationControllerTests.cs
  tests/Integration/Controllers/Doctor/DoctorAuthControllerTests.cs
  tests/Integration/Controllers/Doctor/VaccinationSlotsControllerTests.cs
  tests/Integration/Controllers/Patient/PatientAuthControllerTests.cs
  tests/Integration/Controllers/Patient/PatientControllerTests.cs
  tests/Integration/Controllers/Patient/VaccinationControllerTests.cs
  tests/Unit/Middleware/JwtMiddlewareTest.cs
  tests/Unit/Services/Admin/AdminAuthServiceTest.cs
  tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs
  tests/Unit/Services/Admin/AdminPatientsServiceTest.cs
  tests/Unit/Services/Admin/SettingServiceTest.cs
  tests/Unit/Services/BugServiceTest.cs
  tests/Unit/Services/CommonVaccinationServiceTest.cs
  tests/Unit/Services/Doctor/DoctorAuthServiceTest.cs
  tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs
  tests/Unit/Services/Patient/PatientAuthServiceTest.cs
  tests/Unit/Services/Patient/PatientServiceTest.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
  tests/backend-tests.csproj
Labels: enhancement

#55 [] fix discrepancy in tests regarding pdf generation
  tests/Integration/Controllers/Patient/VaccinationControllerTests.cs
Labels: hotfix

#57 [SP-53] Change vaccination slot by admin
  app/Controllers/Admin/AdminVaccinationController.cs
  app/Controllers/Patient/VaccinationController.cs
  app/Dto/Requests/ChangeSlotRequest.cs
  app/Helpers/Program.cs
  app/Helpers/Semaphores.cs
  app/Postman/IO.postman_collection.json
  app/Services/Admin/AdminVaccinationService.cs
  app/Services/Patient/PatientVaccinationService.cs
  tests/Unit/Services/Admin/AdminVaccinationServiceTest.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: enhancement

#58 [SP-159] Confirm registration
  app/Controllers/Patient/PatientController.cs
  app/Database/Seeder.cs
  app/Dto/Requests/Patient/ConfirmRegistrationRequest.cs
  app/Exceptions/UnauthorizedException.cs
  app/Helpers/FrontendUrlsSettings.cs
  app/Helpers/Program.cs
  app/Models/Accounts/PatientModel.cs
  app/Postman/IO.postman_collection.json
  app/Services/AuthService.cs
  app/Services/Patient/PatientAuthService.cs
  app/Services/Patient/PatientService.cs
  app/appsettings.json
  tests/Helpers/DbHelper.cs
  tests/Unit/Services/Admin/AdminPatientsServiceTest.cs
  tests/Unit/Services/Patient/PatientAuthServiceTest.cs
  tests/Unit/Services/Patient/PatientServiceTest.cs
Labels: enhancement

#60 [SP-212] Get vaccination history
  app/Controllers/Admin/AdminVaccinationController.cs
  app/Dto/Requests/Admin/FilterVaccinationsRequest.cs
  app/Dto/Responses/Admin/Vaccination/GetVaccinationsResponse.cs
  app/Dto/Responses/Admin/Vaccination/VaccinationSlotResponse.cs
  app/Postman/IO.postman_collection.json
  app/Services/Admin/AdminVaccinationService.cs
  app/backend.csproj
  tests/Unit/Services/Admin/AdminVaccinationServiceTest.cs
Labels: enhancement

#64 [SP-217] show patients gets params from query
  app/Postman/IO.postman_collection.json
  app/Services/Admin/AdminPatientsService.cs
Labels: hotfix

#65 [SP-218] finishing touches to our ITs
  app/Dto/Requests/ChangeSlotRequest.cs
  tests/Integration/Controllers/Admin/AdminVaccinationController.cs
  tests/Integration/Controllers/Doctor/DoctorVaccinationController.cs
  tests/Integration/Controllers/Patient/PatientControllerTests.cs
  tests/Unit/Services/Admin/AdminVaccinationServiceTest.cs
  tests/Unit/Services/Doctor/DoctorVaccinationServiceTest.cs
Labels: enhancement

#66 [SP-221] Visual improvements in PDF files
  app/Helpers/PdfGenerators/CertificateGenerator.cs
  app/Helpers/PdfGenerators/PdfGeneratorHelper.cs
  app/Helpers/PdfGenerators/ReportGenerator.cs
  app/Resources/Logo.png
  app/backend.csproj
Labels: enhancement
