Repository szczepienia-pw/backend, pull requests merged in 2022-04, with the labels that each got.

#24 [SP-32] Patient account edition
  app/Controllers/Admin/AdminPatientController.cs
  app/Controllers/Patient/PatientController.cs
  app/Controllers/Patient/PatientRegistationController.cs
  app/Database/Seeder.cs
  app/Dto/Requests/Patient/Address/PatientAddressRequest.cs
  app/Dto/Requests/Patient/Address/PatientRegistrationAddressRequest.cs
  app/Dto/Requests/Patient/PatientRegistrationAddressRequest.cs
  app/Dto/Requests/Patient/PatientRegistrationRequest.cs
  app/Dto/Requests/Patient/PatientRequest.cs
  app/Models/Accounts/PatientModel.cs
  app/Models/Visits/VaccinationModel.cs
  app/Models/Visits/VaccinationSlotModel.cs
  app/Postman/IO.postman_collection.json
  app/Program.cs
  app/Services/Patient/PatientRegistrationService.cs
  app/Services/Patient/PatientService.cs
  app/backend.csproj
  tests/Helpers/DbHelper.cs
  tests/Unit/Services/Patient/PatientServiceTest.cs
  tests/backend-tests.csproj
Labels: enhancement

#26 [SP-134] added GET admin -> doctor / doctors
  app/Controllers/Admin/AdminDoctorsController.cs
  app/Dto/Requests/Doctor/VaccinationSlot/FilterVaccinationSlotsRequest.cs
  app/Dto/Requests/PaginationRequest.cs
  app/Dto/Responses/Doctor/DoctorResponse.cs
  app/Models/Accounts/PatientModel.cs
  app/Postman/IO.postman_collection.json
  app/Services/Admin/AdminDoctorsService.cs
  tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs
Labels: enhancement

#27 [SP-136] fix pagination request
  app/Controllers/Admin/AdminDoctorsController.cs
  app/Postman/IO.postman_collection.json
Labels: hotfix

#28 [SP-139] fixed mySql error on CheckDuplicate
  app/Database/DataContextExtensions.cs
  app/Helpers/EnumberableExtensions.cs
  app/Models/Accounts/AccountModel.cs
  app/Models/BaseModel.cs
  app/Models/SettingModel.cs
  app/Models/Vaccines/VaccineModel.cs
  app/Models/Visits/VaccinationModel.cs
  app/Models/Visits/VaccinationSlotModel.cs
  app/Services/Doctor/VaccinationSlotService.cs
  app/backend.csproj
Labels: hotfix

#30 quick fix for LoadFields
  app/Database/DataContextExtensions.cs
  app/backend.csproj
Labels: hotfix

#33 [SP-145] Basic API tests in Postman
  app/Postman/IO.postman_collection.json
Labels: enhancement

#32 [SP-123] Code refactor (extension methods)
  app/Controllers/Doctor/DoctorAuthController.cs
  app/Controllers/Patient/PatientAuthController.cs
  app/Postman/IO.postman_collection.json
  app/Services/Admin/AdminDoctorsService.cs
  app/Services/Patient/PatientService.cs
  tests/UnitTest1.cs
Labels: enhancement

#34 [SP-24] Vaccination visit registration
  app/Controllers/Patient/VaccinationController.cs
  app/Database/Seeder.cs
  app/Dto/Requests/Patient/ReserveSlotRequest.cs
  app/Dto/Requests/Patient/ShowVaccinesRequest.cs
  app/Dto/Responses/Common/Vaccination/VaccineResponse.cs
  app/Dto/Responses/Doctor/Vaccination/VaccinationResponse.cs
  app/Dto/Responses/Doctor/Vaccination/VaccinationSlotResponse.cs
  app/Dto/Responses/Patient/Vaccination/AvailableSlotResponse.cs
  app/Dto/Responses/Patient/Vaccination/ShowAvailableVaccinesResponse.cs
  app/Exceptions/NotFoundException.cs
  app/Models/Vaccines/DiseaseEnum.cs
  app/Postman/IO.postman_collection.json
  app/Program.cs
  app/Services/Doctor/VaccinationSlotService.cs
  app/Services/Patient/PatientAuthService.cs
  app/Services/Patient/PatientService.cs
  app/Services/Patient/VaccinationService.cs
  app/appsettings.json
  tests/Helpers/DbHelper.cs
  tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs
  tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: enhancement

#25 [SP-126] added admin -> patient CRUD
  app/Controllers/Admin/AdminPatientController.cs
  app/Dto/Requests/Admin/Patient/ShowPatientsRequest.cs
  app/Models/Accounts/PatientModel.cs
  app/Models/Visits/VaccinationModel.cs
  app/Postman/IO.postman_collection.json
  app/Program.cs
  app/Services/Admin/AdminPatientsService.cs
  tests/Helpers/DbHelper.cs
  tests/Unit/Services/Admin/AdminPatientsServiceTest.cs
Labels: enhancement

#35 [SP-139] Fix for lazyloading in response
  app/Models/BaseModel.cs
  app/Services/Admin/AdminDoctorsService.cs
  tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs
Labels: hotfix

#36 [SP-148] Fix response in Show available vaccines request
  app/Dto/Responses/Patient/Vaccination/ShowAvailableVaccinesResponse.cs
  app/Postman/IO.postman_collection.json
  app/Services/Patient/VaccinationService.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: bug, hotfix

#37 [SP-124] E-mail validation
  app/Helpers/PeselValidator.cs
  app/Helpers/Validator.cs
  app/Services/Admin/AdminDoctorsService.cs
  app/Services/Patient/PatientService.cs
  tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs
  tests/Unit/Services/Patient/PatientServiceTest.cs
Labels: enhancement

#38 [SP-28] Added canceling vaccination visit with testing
  app/Controllers/Patient/VaccinationController.cs
  app/Postman/IO.postman_collection.json
  app/Services/BugService.cs
  app/Services/Patient/VaccinationService.cs
  app/appsettings.json
  tests/Helpers/DbHelper.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: enhancement

#39 [SP-151] Discrepancy with our API regarding Admin/getPatients
  app/Controllers/Admin/AdminPatientController.cs
Labels: hotfix

#40 [SP-152] Doctor / deleteSlot proxy error fix
  app/Services/Doctor/VaccinationSlotService.cs
Labels: hotfix

#41 [SP-153] incompatible API endpoint patient/show available vaccines
  app/Controllers/Patient/VaccinationController.cs
  app/Helpers/Mailer.cs
  app/Services/BugService.cs
  app/Services/Patient/VaccinationService.cs
  tests/Unit/Services/BugServiceTest.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: hotfix

#42 [SP-156] return null instead of {} if vaccination is null
  app/Dto/Responses/Doctor/Vaccination/VaccinationSlotResponse.cs
Labels: hotfix

#50 [SP-178] Change to common mailtrap account
  app/appsettings.json
Labels: enhancement

#47 [SP-30] Download vaccine certificate
  app/Controllers/Patient/VaccinationController.cs
  app/Helpers/CertificateGenerator.cs
  app/Postman/IO.postman_collection.json
  app/Services/Patient/VaccinationService.cs
  app/backend.csproj
  tests/backend-tests.csproj
Labels: enhancement

#48 [SP-175] Get vaccination slots as a common endpoint
  app/Controllers/CommonVaccinationController.cs
  app/Controllers/Patient/VaccinationController.cs
  app/Postman/IO.postman_collection.json
  app/Program.cs
  app/Services/CommonVaccinationService.cs
  app/Services/Patient/VaccinationService.cs
  tests/Unit/Services/CommonVaccinationServiceTest.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: enhancement

#49 [SP-48] Vaccinate patient
  app/Controllers/Doctor/VaccinationSlotsController.cs
  app/Dto/Requests/Doctor/VaccinationSlot/VaccinatePatientRequest.cs
  app/Models/Vaccines/DiseaseEnum.cs
  app/Models/Visits/StatusEnum.cs
  app/Postman/IO.postman_collection.json
  app/Services/Doctor/VaccinationSlotService.cs
  app/Services/Patient/VaccinationService.cs
  tests/Helpers/DbHelper.cs
  tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs
  tests/Unit/Services/Patient/VaccinationServiceTest.cs
Labels: enhancement

#46 [SP-154] Add mail notification when deleting doctor with reserved slots
  .gitignore
  app/Models/Visits/VaccinationSlotModel.cs
  app/Services/Admin/AdminDoctorsService.cs
  tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs
Labels: enhancement
