Repository szczepienia-pw/backend, pull requests merged in 2022-03, with the labels that each got.

#1 SP-95 Create backend wireframe
  .gitignore
  Controllers/WeatherForecastController.cs
  Database/DataContext.cs
  Migrations/20220308184126_v1.Designer.cs
  Migrations/20220308184126_v1.cs
  Migrations/20220308184411_v2.Designer.cs
  Migrations/20220308184411_v2.cs
  Migrations/20220308184759_v3.Designer.cs
  Migrations/20220308184759_v3.cs
  Migrations/20220308191558_v4.Designer.cs
  Migrations/20220308191558_v4.cs
  Migrations/20220308191823_v5.Designer.cs
  Migrations/20220308191823_v5.cs
  Migrations/20220308192150_v6.Designer.cs
  Migrations/20220308192150_v6.cs
  Migrations/20220308192249_v7.Designer.cs
  Migrations/20220308192249_v7.cs
  Migrations/20220308192556_v8.Designer.cs
  Migrations/20220308192556_v8.cs
  Migrations/DataContextModelSnapshot.cs
  Models/Accounts/Account.cs
  Models/Accounts/AdditionalData/Address.cs
  Models/Accounts/Admin.cs
  Models/Accounts/Doctor.cs
  Models/Accounts/Patient.cs
  Models/Vaccines/Disease.cs
  Models/Vaccines/Vaccine.cs
  Models/Visits/Status.cs
  Models/Visits/Vaccination.cs
  Models/Visits/VaccinationSlot.cs
  Program.cs
  Properties/launchSettings.json
  Startup.cs
  WeatherForecast.cs
  appsettings.Development.json
  appsettings.json
  backend.csproj
  backend.sln
Labels: enhancement

#2 Add license
  LICENSE.md
Labels: enhancement

#8 Update README
  LICENSE.md
  README.md
Labels: documentation

#11 SP-115 Remove EF6
  app/Services/Doctor/VaccinationSlotService.cs
  app/backend.csproj
Labels: bug

#12 Feature/SP-108 - Unit testy dodawania slotów
  tests/Helpers/DbHelper.cs
  tests/Unit/Middleware/JwtMiddlewareTest.cs
  tests/Unit/Services/Doctor/DoctorAuthServiceTest.cs
  tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs
Labels: enhancement

#15 [SP-118] Vaccination slots list (with deleting)
  app/Controllers/Doctor/VaccinationSlotsController.cs
  app/Dto/Requests/Doctor/VaccinationSlot/FilterVaccinationSlotsRequest.cs
  app/Dto/Requests/Doctor/VaccinationSlot/NewVaccinationSlotRequest.cs
  app/Dto/Responses/Doctor/NewVaccinationSlotResponse.cs
  app/Dto/Responses/Doctor/VaccinationSlot/VaccinationSlotResponse.cs
  app/Dto/Responses/PaginatedResponse.cs
  app/Dto/Responses/SuccessResponse.cs
  app/Exceptions/BasicException.cs
  app/Exceptions/ConflictException.cs
  app/Exceptions/NotFoundException.cs
  app/Helpers/PaginatedList.cs
  app/Postman/IO.postman_collection.json
  app/Services/Doctor/VaccinationSlotService.cs
  tests/Helpers/DbHelper.cs
  tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs
Labels: enhancement

#14 [SP-122] Improvements for adding vaccination slots
  app/Services/Doctor/VaccinationSlotService.cs
  tests/Unit/Services/Doctor/VaccinationSlotServiceTest.cs
Labels: bug

#19 [SP-20] Patient registration
  app/Controllers/Patient/PatientRegistationController.cs
  app/Dto/Requests/Patient/PatientRegistrationAddressRequest.cs
  app/Dto/Requests/Patient/PatientRegistrationRequest.cs
  app/Helpers/EnumberableExtensions.cs
  app/Helpers/PeselValidator.cs
  app/Models/Accounts/PatientModel.cs
  app/Postman/IO.postman_collection.json
  app/Program.cs
  app/Services/Admin/AdminDoctorsService.cs
  app/Services/Doctor/VaccinationSlotService.cs
  app/Services/Patient/PatientRegistrationService.cs
Labels: enhancement

#21 [SP-58] edycja danych lekarza
  app/Controllers/Admin/AdminDoctorsController.cs
  app/Dto/Requests/Admin/Doctor/CreateDoctorRequest.cs
  app/Dto/Requests/Admin/Doctor/EditDoctorRequest.cs
  app/Models/Accounts/DoctorModel.cs
  app/Postman/IO.postman_collection.json
  app/Services/Admin/AdminDoctorsService.cs
  tests/Unit/Services/Admin/AdminDoctorsServiceTest.cs
Labels: enhancement

#18 [SP-63] Bug reporting
  app/Controllers/Admin/SettingController.cs
  app/Controllers/BugController.cs
  app/Controllers/Doctor/DoctorAuthController.cs
  app/Database/DataContext.cs
  app/Database/Seeder.cs
  app/Dto/Requests/SendBugRequest.cs
  app/Helpers/AuthorizeAttribute.cs
  app/Helpers/MailSettings.cs
  app/Helpers/Mailer.cs
  app/Models/SettingModel.cs
  app/Postman/IO.postman_collection.json
  app/Program.cs
  app/Services/Admin/SettingService.cs
  app/Services/BugService.cs
  app/appsettings.json
  app/backend.csproj
  tests/Helpers/DbHelper.cs
  tests/Unit/Services/Admin/SettingServiceTest.cs
  tests/Unit/Services/BugServiceTest.cs
Labels: enhancement

#23 [SP-131] Poprawki do endpointa z vaccination-slots
  app/Database/Seeder.cs
  app/Dto/Responses/PaginatedResponse.cs
  app/Models/Visits/VaccinationSlotModel.cs
  app/Program.cs
  app/Validators/Requests/Doctor/VaccinationSlot/FilterVaccinationSlotValidator.cs
  app/backend.csproj
Labels: enhancement
